{% set name = "compas_eve" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_eve-{{ version }}.tar.gz
  sha256: 8f121d25749e051a92f78c5bf8c36c27427a91aa5af6445e604a16d3689c8573

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - compas
    - paho-mqtt
    - python >=3.6

test:
  imports:
    - compas_eve
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_eve
  summary: 'COMPAS Event Extensions: event-based communication infrastructure for the COMPAS framework'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
