{% set name = "compas_eve" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_eve-{{ version }}.tar.gz
  sha256: 40ad0a387b0b831b97304bff0a5bfaa3e8ba9128bd4004920eea3acf90e0ac56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - compas
    - paho-mqtt >=1,<2
    - python >=3.6

test:
  imports:
    - compas_eve
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_eve
  summary: 'COMPAS Event Extensions: event-based communication infrastructure for the COMPAS framework'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
